import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";

import "./globals.css";
import { ShootingStars } from "@/components/elements/shooting-stars";
import { StarsBackground } from "@/components/elements/stars-background";
import Footer from "@/components/layout/footer";

const atkinson = Atkinson_Hyperlegible({
  subsets: ["latin"],
  variable: "--font-atkinson",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={atkinson.variable}>
      <body className={`${atkinson.className} relative antialiased bg-background w-screen h-screen flex flex-col`}>
        <ShootingStars />
        <StarsBackground />
        {children}
      </body>
    </html>
  );
}
