import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import StarsWrapper from "@/components/layout/stars-wrapper";

const atkinson = Atkinson_Hyperlegible({
  subsets: ["latin"],
  variable: "--font-atkinson",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${atkinson.variable} scroll-smooth`}>
      <body className={`${atkinson.className} relative antialiased bg-background w-screen h-screen flex flex-col`}>
        <StarsWrapper />
        {children}
        <Toaster position="top-center" offset={140} />
      </body>
    </html>
  );
}
