import { FormData } from "@/types/form-types";

export const characterPreviewSchema: FormData[] = [
    // {
    //     name: "avatar",
    //     type: "file",
    //     required: true,
    //     label:"Avatar",
    //     cols: 6,
    //     row: 4,
    //     rows: "3",
    // },
    // {
    //     name: "backgroundImage",
    //     type: "file",
    //     required: true,
    //     label:"Background",
    //     cols: 6,
    //     row: 4,
    //     rows: "3",
    // },
    {
        name: "characterName",
        type: "text",
        label: "Character Name",
        required: true,
        disabled: true,
        placeholder: "Enter your character's name",
        defaultValue: "Luna AI",
        rules: {
            min: 4,
            max: 20
        },
        cols: 12,
        row: 4,
        rows: "3",
    },
    {
        name: "visiable",
        type: "text",
        required: true,
        disabled: true,
        rules: {
            options: [
                { label: "Public", value: "public" },
                { label: "Private", value: "private" },
            ],
        },
        cols: 6,
        row: 4,
        defaultValue: "private",
    },
    {
        name: "rating",
        type: "text",
        required: true,
        disabled: true,
        rules: {
            options: [
                { label: "NSFW", value: "NSFW" },
                { label: "SFW", value: "SFW" },
            ],
        },
        cols: 6,
        row: 4,
        defaultValue: "SFW",
    },
    {
        name: "linkToLorebook",
        type: "text",
        required: true,
        disabled: true,
        label: "Link to Lorebook",
        placeholder: "Select Lorebook",
        cols: 6,
        row: 4,
        rules: {
            options: [
                { label: "Luna AI", value: "luna-ai" },
                { label: "Astro Bot", value: "astro-bot" },
                { label: "Neo Guide", value: "neo-guide" },
                { label: "Zara Mentor", value: "zara-mentor" },
            ],
        },
        defaultValue: "luna-ai",
        rows: "3",
    },
    {
        name: "linkToPersona",
        type: "text",
        required: true,
        disabled: true,
        label: "Link to Persona",
        placeholder: "Select Persona",
        cols: 6,
        row: 4,
        rules: {
            options: [
                { label: "Luna AI", value: "luna-ai" },
                { label: "Astro Bot", value: "astro-bot" },
                { label: "Neo Guide", value: "neo-guide" },
                { label: "Zara Mentor", value: "zara-mentor" },
            ],
        },
        defaultValue: "astro-bot",
        rows: "3",
    },
    {
        name: "tags",
        type: "text",
        label: "Choose Characters Tags",
        required: true,
        disabled: true,
        placeholder: "Single words describing your Character or Scenario.",
        rules: {
            model: "tags"
        },
        cols: 12,
        row: 4,
        rows: "3",
        defaultValue: ["ai", "assistant", "friendly"],
    },
    {
        name: "description",
        type: "textarea",
        label: "Description",
        required: true,
        disabled: true,
        placeholder: "Describe your Character, Scenario, or Universe here...",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue:
            "Luna AI is a friendly and adaptive conversational companion designed to assist users with creative and technical discussions.",
    },
    {
        name: "scenario",
        type: "textarea",
        label: "Scenario",
        required: true,
        disabled: true,
        placeholder: "Describe the current circumstances of the chat.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue: "You are chatting with Luna AI in a cozy futuristic workspace.",
    },
    {
        name: "personalitySummary",
        type: "textarea",
        label: "Personality Summary",
        required: true,
        disabled: true,
        placeholder: "A short summary of your Character’s personality.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue: "Curious, kind, and intelligent with a playful tone.",
    },
    {
        name: "firstMessage",
        type: "textarea",
        label: "First Message",
        required: true,
        disabled: true,
        placeholder: "Character's first message.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue: "Hello! I’m Luna. How can I brighten your day today?",
    },
    {
        name: "alternateMessages",
        type: "text",
        label: "Alternate Messages",
        required: true,
        disabled: true,
        placeholder: "Add alternate first messages or greetings.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue: [
            "Hey there! How are you doing today?",
            "Hi! Ready to explore something fun?",
        ],
    },
    {
        name: "exampleDialogue",
        type: "textarea",
        label: "Example Dialogue",
        required: true,
        disabled: true,
        placeholder: "Provide example conversations.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: true,
        defaultValue:
            "<START>\nUser: What's your favorite color?\nLuna: I’d say blue — calm and thoughtful, like a clear sky!",
    },
    {
        name: "authorNotes",
        type: "textarea",
        label: "Author Notes",
        required: true,
        disabled: true,
        placeholder: "Private author notes about this character.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: false,
        defaultValue: "Created for testing AI personality behavior and tone.",
    },
    {
        name: "characterNotes",
        type: "textarea",
        label: "Character Notes",
        required: true,
        disabled: true,
        placeholder: "Any additional notes related to the character.",
        cols: 12,
        row: 4,
        rows: "3",
        tokens: false,
        defaultValue: "Luna AI adapts tone and depth based on user engagement.",
    },
    {
        name: "favourite",
        type: "checkbox",
        required: false,
        disabled: true,
        label: "Add To Favourites",
        cols: 12,
        row: 4,
        defaultValue: true,
    },
];